### PR TITLE
updates to curl request to influx and changed measurement naming convention

### PR DESCRIPTION
**Pull request by naveenkashyap**
I've made changes that reflect the updates to Influx by avoiding deprecated REST calls. 
I've also changed the naming convention of the measurements within Influx to make them more easily query-able

### CODE REVIEW

**Comment by TysonJones** [comment]
Hi Naveen,

Can I ask about the reasoning behind this change?

image

Thanks,
Tyson

**Comment by naveenkashyap** [comment]
@TysonJones Influx deprecated `CREATE DATABASE IF NOT EXISTS` leaving only `CREATE DATABASE`.

**Comment by TysonJones** [comment]
Sure. Is everything requiredly POST? I think urllib2 assumes POST if you pass data

**Comment by naveenkashyap** [comment]
I thought so too. But when the request is made, influx complains about the request being GET. I think what is happening is that the call is actually going through a redirect somewhere we cannot access and, unless it is explicitly stated, the call is converted from POST to GET. This was a lazy work around as I am currently working on something else. But I will work on this as it seems there must be a more robust way of handling this.

**Comment by TysonJones** [comment]
Oh weird. Thanks for the updates! :)

**Pull request merged**
